name: Translation Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run build script
        id: build_translation_file
        run: |
          python ./generate_locale.py ./translation/ko ./translation.json

      - name: Gzip compress the output file
        run: gzip -k translation.json

      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_release_tag.outputs.release_tag }}
          name: Release ${{ steps.generate_release_tag.outputs.release_tag }}
          body: "Translated ${{ steps.build_translation_file.outputs.stats }}"
          artifacts: |
            translation.json
            translation.json.gz

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
